version: '3'

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src
    command: yarn start:dev
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./docker/postgres/migrations:/docker-entrypoint-initdb.d
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data:/data
