export enum E_DB_TABLES {
  USERS = 'users',
  USER_ROLES = 'user_roles',
  ROLES = 'roles',
  ROLE_PERMISSIONS = 'role_permissions',
  PERMISSIONS = 'permissions',
  COURSES = 'courses',
  COURSE_TEACHERS = 'course_teachers',
  COURSE_ACTIVITY = 'course_activity',
  CLASSES = 'classes',
  SCHEDULE = 'schedule',
  STUDENT_SCHEDULE = 'student_schedule',
}

export enum E_CUSTOM_ERROR_CODES {
  SCHEDULE_TIME_TOO_SHORT = 'C0001',
  SCHEDULE_TIME_TOO_LONG = 'C0002',
  SCHEDULE_TIME_IN_THE_PAST = 'C0003',
  SCHEDULE_CONFLICT = 'C0004',
  TEACHER_NOT_IN_COURSE = 'C0005',
  USER_NOT_A_TEACHER = 'C0006',
  TEACHER_REQS_UNSATISFIED = 'C0007',
  TEACHER_REQS_CONFLICT = 'C0008',
}

export enum E_POSTGRES_ERROR_CODES {
  UNIQUE_CONSTRAINT = '23505',
  INVALID_TEXT_REPRESENTATION = '22P02',
  FOREIGN_KEY_VIOLATION = '23503',
  STRING_DATA_RIGHT_TRUNCATION = '22001',
}

export enum E_SQLITE_ERROR_CODES {
  UNIQUE_CONSTRAINT = 'SQLITE_CONSTRAINT',
  FOREIGN_KEY_VIOLATION = 'SQLITE_CONSTRAINT_FOREIGNKEY',
  STRING_DATA_RIGHT_TRUNCATION = 'SQLITE_TOOBIG',
}
