import { E_DB_TABLES } from '../constants';
import { Entity, PrimaryColumn } from 'typeorm';

export enum E_PERMISSION_ENTITY_KEYS {
  NAME = 'name',
}

export enum E_PERMISSION {
  EDIT_USER = 'EDIT_USER',
  EDIT_CLASS = 'EDIT_CLASS',
  EDIT_COURSE = 'EDIT_COURSE',
  ADD_GUARANTOR = 'ADD_GUARANTOR',
  EDIT_ACTIVITY = 'EDIT_ACTIVITY',
  EDIT_COURSE_TEACHER = 'EDIT_COURSE_TEACHER',
  DEFINE_COURSE_REQUIREMENTS = 'DEFINE_COURSE_REQUIREMENTS',
  ADD_PERSONAL_REQUIREMENTS = 'ADD_PERSONAL_REQUIREMENTS',
  PLACE_SCHEDULE_ACTIVITIES = 'PLACE_SCHEDULE_ACTIVITIES',
  ASSIGN_SCHEDULE_CLASSES = 'ASSIGN_SCHEDULE_CLASSES',
  EDIT_PERSONAL_COURSES = 'EDIT_PERSONAL_COURSES',
  VIEW_PERSONAL_SCHEDULE = 'VIEW_PERSONAL_SCHEDULE',
  VIEW_ANNOTATION = 'VIEW_ANNOTATION',
}

@Entity({ name: E_DB_TABLES.PERMISSIONS })
export class Permission {
  @PrimaryColumn()
  [E_PERMISSION_ENTITY_KEYS.NAME]: string;
}
